apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  creationTimestamp: null
  name: minio-tenant-2
  namespace: minio-tenant-2
scheduler:
  name: ""
spec:
  certConfig: {}
  credsSecret:
    name: minio-tenant-2-creds-secret
  image: minio/minio:RELEASE.2022-03-03T21-21-16Z
  imagePullSecret: {}
  mountPath: /export
  pools:
  - affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: v1.min.io/tenant
              operator: In
              values:
              - minio-tenant-2
          topologyKey: kubernetes.io/hostname
    resources: {}
    servers: 3
    volumeClaimTemplate:
      apiVersion: v1
      kind: persistentvolumeclaims
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: "1789569706"
        storageClassName: local-path
      status: {}
    volumesPerServer: 2
  requestAutoCert: true
  users:
  - name: minio-tenant-2-user-1

---
apiVersion: v1
data:
  accesskey: ZTQ0ZWIwMWMtYWU0OS00MWJkLWExMjYtYzA1ZWNiZDNmY2Y4
  secretkey: NjllYTJiYzItZjYzNC00NTE3LWE4NTktOTgyNjQyYzczNzYz
kind: Secret
metadata:
  creationTimestamp: null
  name: minio-tenant-2-creds-secret
  namespace: minio-tenant-2

---
apiVersion: v1
data:
  CONSOLE_ACCESS_KEY: YWRtaW4=
  CONSOLE_SECRET_KEY: NGZlNzk0NzItYWQxZC00MjQ5LWIyNjAtMGYzNzgwNzVkZTEz
kind: Secret
metadata:
  creationTimestamp: null
  name: minio-tenant-2-user-1
  namespace: minio-tenant-2

